spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/observability
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
  application:
    name: auth-service
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


server:
  port: 9090

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831
    log-spans: true
    enabled: true
  zipkin:
    http-sender:
      baseUrl: http://localhost:9411
    boundary-sampler.rate: 1.0
  enabled: true