version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:1.9
    ports:
      - '16686:16686'
      - '14250:14250'
      - '6831:6831/udp'

  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'

volumes:
  db:
    driver: local