version: '3.8'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:1.9
    ports:
      - '16686:16686'
      - '14250:14250'
      - '6831:6831/udp'

  zipkin:
    image: openzipkin/zipkin
    ports:
      - '9411:9411'

  redis:
    image: redis
    ports:
      - '6379:6379'

  auth-service:
    build: auth-service
    ports:
      - '9090:9090'
    depends_on:
      - print-service
      - redis
      - zipkin
      - jaeger
      - postgres
    environment:
      - SPRING_DATASOURCE_URL="jdbc:postgresql://postgres:5432/observability"
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - OPENTRACING_JAEGER_UDP_SENDER_HOST=jaeger
      - OPENTRACING_JAEGER_UDP_SENDER_PORT=6831
      - OPENTRACING_ZIPKIN_HTTP_SENDER_URL="http://zipkin:9411"
      - SPRING_REDIS_HOST=redis

  print-service:
    build: print-service
    ports:
      - '9091:9091'

volumes:
  db:
    driver: local