server:
  port: 9091

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: print-service

opentracing:
  jaeger:
    udp-sender:
      host: localhost
      port: 6831
    log-spans: true
    enabled: true
  enabled: true